### ISSUE TITLE
[1.19.2] Phase Block crash

### ISSUE THREAD

**Issue by itsdinkd** [Talia-12/Hexal#58]
found this in my server. seems a player tried to cast phase block and the server crashed in my modpack, AQM2 

https://gist.github.com/itsdinkd/b6e6fab656f1b446cec14ce9d57b8996

**Comment by Talia-12** [comment]
Fixed for the next release, but until then including the [lib39 ](https://modrinth.com/mod/lib39/versions) mod will fix it as well.

**Comment by itsdinkd** [comment]
Still crashing and i blacklisted Phase Block... I am not adding lib39 as I don't want to add another library if I can just blacklist the spell.
